spring:
  application:
    name: dream-catcher-backend

  datasource:
    url: jdbc:postgresql://localhost:5433/dreamcatcher
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true 

  cache:
    type: simple

server:
  port: 8080

logging:
  level:
    com.dreamcatcher: DEBUG
    org.springframework.web: INFO

jwt:
  secret: ${JWT_SECRET:}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}   # 24h domyślnie

external-api:
  weatherapi:
    base-url: https://api.weatherapi.com/v1
    api-key: ${WEATHERAPI_KEY:}
